SET VAR_START_DATE ='01-JAN-2021';
SET VAR_END_DATE = GETDATE();

create OR REPLACE table "JBML"."PUBLIC"."MONTHLYTXNCE" AS 

with a_cte (TRANSDATE,EXPENSEID,REIMBURSABLE,TOTALAMT,CURRENCYCODE) as
(SELECT E.EXP_DATE AS TRANSDATE, E.EXP_PK AS EXPENSEID, E.EXP_REIMBURSABLE AS REIMBURSABLE, E.EXP_AMOUNT AS TOTALAMT, C.CURRENCYTYPE_SUFFIX as CURRENCYCODE
 from "BRONZE_CE"."CE_PROD_01_DBO"."EXP" E
 ,"BRONZE_CE"."CE_PROD_01_DBO"."CURRENCYTYPE" C
 WHERE EXP_DATE>= $var_start_date and EXP_DATE<= $var_end_date
 AND E.EXP_AMOUNT_CURRENCYTYPEFK = C.CURRENCYTYPE_PK
 AND E._FIVETRAN_DELETED ='FALSE'
 AND C._FIVETRAN_DELETED = 'FALSE'
 AND E.EXP_AMOUNT > 0
 
UNION 
 
SELECT E.EXP_DATE AS TRANSDATE, E.EXP_PK AS EXPENSEID, E.EXP_REIMBURSABLE AS REIMBURSABLE, E.EXP_AMOUNT AS TOTALAMT, C.CURRENCYTYPE_SUFFIX as CURRENCYCODE
 from "BRONZE_CE"."CE_PROD_02_DBO"."EXP" E
 ,"BRONZE_CE"."CE_PROD_02_DBO"."CURRENCYTYPE" C
 WHERE EXP_DATE>= $var_start_date and EXP_DATE<= $var_end_date
 AND E.EXP_AMOUNT_CURRENCYTYPEFK = C.CURRENCYTYPE_PK
 AND E._FIVETRAN_DELETED ='FALSE'
 AND C._FIVETRAN_DELETED = 'FALSE'
 AND E.EXP_AMOUNT > 0

UNION 
 
SELECT E.EXP_DATE AS TRANSDATE, E.EXP_PK AS EXPENSEID, E.EXP_REIMBURSABLE AS REIMBURSABLE, E.EXP_AMOUNT AS TOTALAMT, C.CURRENCYTYPE_SUFFIX as CURRENCYCODE
 from "BRONZE_CE"."CE_PROD_03_DBO"."EXP" E
 ,"BRONZE_CE"."CE_PROD_03_DBO"."CURRENCYTYPE" C
 WHERE EXP_DATE>= $var_start_date and EXP_DATE<= $var_end_date
 AND E.EXP_AMOUNT_CURRENCYTYPEFK = C.CURRENCYTYPE_PK
 AND E._FIVETRAN_DELETED ='FALSE'
 AND C._FIVETRAN_DELETED = 'FALSE'
 AND E.EXP_AMOUNT > 0

UNION 
 
SELECT E.EXP_DATE AS TRANSDATE, E.EXP_PK AS EXPENSEID, E.EXP_REIMBURSABLE AS REIMBURSABLE, E.EXP_AMOUNT AS TOTALAMT, C.CURRENCYTYPE_SUFFIX as CURRENCYCODE
 from "BRONZE_CE"."CE_PROD_04_DBO"."EXP" E
 ,"BRONZE_CE"."CE_PROD_04_DBO"."CURRENCYTYPE" C
 WHERE EXP_DATE>= $var_start_date and EXP_DATE<= $var_end_date
 AND E.EXP_AMOUNT_CURRENCYTYPEFK = C.CURRENCYTYPE_PK
 AND E._FIVETRAN_DELETED ='FALSE'
 AND C._FIVETRAN_DELETED = 'FALSE'
 AND E.EXP_AMOUNT > 0)
,
c_cte (CURRENCYCODETO, CURRENCYCODEFROM, DATEEFF, DATEEND, EXRATE)
as
(
select distinct c.CURRENCYCODE as CURRENCYCODETO, cpta.DISBURSEMENTCURRENCYCODE as CURRENCYCODEFROM, cpta.DATEEFFECTIVE as DATEEFF, cpta.DATEEND as DATEEND, cpta.EXCHANGERATETOFIRMCURRENCY AS EXRATE
from "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CURRENCYPTA" cpta
, "BRONZE_CR"."CR_C1_PROD_CHROME_EXPENSE"."TBL_CUSTOMER" c
where cpta.CUSTOMERID = c.CUSTOMERID
and c.CURRENCYCODE = 'USD'
and cpta._FIVETRAN_DELETED = 'FALSE'
)
SELECT  
 YEAR (a_cte.TRANSDATE) as YEAR
, MONTH (a_cte.TRANSDATE) as MONTH
, a_cte.EXPENSEID AS EXPENSEID
, CASE WHEN SUM(case when a_cte.CURRENCYCODE = 'USD' then a_cte.TOTALAMT else a_cte.TOTALAMT*c_cte.EXRATE end) BETWEEN 25 AND 75 THEN '$25 -$75 EXPENSE'  ELSE 'OTHER' END AS EXPENSERANGE
--, CASE WHEN USD_AMOUNT BETWEEN 25 AND 75 THEN '$25 - $75 EXPENSE' ELSE 'GREATER THAN $75 EXPENSE' END AS EXPENSERANGE

from a_cte
left join c_cte on c_cte.CURRENCYCODEFROM = a_cte.CURRENCYCODE 
and c_cte.DATEEFF < a_cte.TRANSDATE 
and c_cte.DATEEND > a_cte.TRANSDATE 

WHERE a_cte.REIMBURSABLE = 'TRUE'
group by YEAR,MONTH,EXPENSEID
ORDER BY YEAR, MONTH;

SELECT YEAR, MONTH, EXPENSERANGE, COUNT(EXPENSEID) AS EXPENSECOUNT FROM "JBML"."PUBLIC"."MONTHLYTXNCE" GROUP BY YEAR, MONTH, EXPENSERANGE ORDER BY YEAR, MONTH, EXPENSERANGE
 